# -*- coding: utf-8 -*-
"""Classification with Neural Networks using Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XCJVAz0JKd_ftZPuK5V-Qcj-lcKy-lFL
"""

import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt
fashion = keras.datasets.fashion_mnist
(xtrain, ytrain), (xtest, ytest) = fashion.load_data()

import numpy as np

# Normalize the image
image_normalized = image / 1.0

# Display the normalized image
plt.imshow(image_normalized, cmap='gray')
plt.axis('off')
plt.show()

import matplotlib.pyplot as plt

# Assuming xtrain and ytrain are already defined
imgIndex = 9  # You can change this index to display different images
image = xtrain[imgIndex]

# Print the label of the image
print("Image Label:", ytrain[imgIndex])

# Display the image without normalization or filtering
plt.imshow(image, cmap='gray')  # Use cmap='gray' for grayscale images
plt.axis('off')  # Turn off axis
plt.show()

imgIndex = 900
image = xtrain[imgIndex]
print("Image Label :",ytrain[imgIndex])
plt.imshow(image)

print(xtrain.shape)
print(xtest.shape)

model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=[28, 28]),
    keras.layers.Dense(300, activation="relu"),
    keras.layers.Dense(100, activation="relu"),
    keras.layers.Dense(10, activation="softmax")
])
print(model.summary())

xvalid, xtrain = xtrain[:5000]/255.0, xtrain[5000:]/255.0
yvalid, ytrain = ytrain[:5000], ytrain[5000:]

model.compile(loss="sparse_categorical_crossentropy",
              optimizer="sgd",
              metrics=["accuracy"])
history = model.fit(xtrain, ytrain, epochs=30,
                    validation_data=(xvalid, yvalid))

new = xtest[:5]
predictions = model.predict(new)
print(predictions)

classes = np.argmax(predictions, axis=1)
print(classes)



